Qa python homework 2
SushkaVlad/2020-1-Atom-QA-Python-V-Sushkevich pull request #2
Opened 2020-10-12 21:33 UTC by SushkaVlad

#Домашнее задание №2

Прошу @snicks92 или "z1ll1 проверить его.

Что было сделано:
Реализован паттерн PageObject
Были написаны все требуемые тесты.
Тесты запускаются в несколько потоков.

p.s. Искренне сожалею о просроченном дедлайне, ненастроенный .gitignore меня подвел

2020-10-24 01:11 UTC, SK1995 requested changes
В целом неплохая работа, спасибо.

Оставил пару комментариев по коду, можно поправить, если хочешь балл повыше.
И еще у меня почему-то не проходит тест test_create_company, вот [трейсбек](https://pastebin.com/cqVqC3z8).

2020-10-24 01:11 UTC, SK1995 commented on тестирование/Hw2/code/ui/fixtures.py
> +        # driver = webdriver.Remote(command_executor='http://127.0.0.1:4444/wd/hub/',
А чего селеноид не настроил?
Это же очень просто :)

Нужно всего 2 вещи:
1) Прокинуть опцию --selenoid в `conftest.py`  в хук `pytest_addoption` (аналогично `browser` и `browser_ver`), положить ее в фикстуру `config`.
2) Поместить этот закомментированный код под ` if`, прочитав значение параметра selenoid из `config`.

Ну и поставить себе селеноид конечно, чтобы проверить, что все работает.
На линуксе его можно вот так установить, например:
```bash
curl -s https://aerokube.com/cm/bash | bash && ./cm selenoid start --vnc
```

2020-10-24 01:11 UTC, SK1995 commented on тестирование/Hw2/code/ui/pages/create_company_page.py
> +        music_upload.send_keys(r"C:\Users\USER\Desktop\информатика\Python\тестирование\Hw2\code\sources\music1.mp3")
У меня на вызове этой функции тест `test_create_company` падает, т. к. этого файла у меня нет.
Причем в репе даже есть `тестирование/Hw2/code/sources/music1.mp3`, надо его и использовать.

Чтобы это работало у всех, лучше всего не хардкодить путь к файлу, а вычислять его относительно текущего файла, например вот так:
```python
        curr_dir = pathlib.Path(__file__).parent
        mp3_path = curr_dir.parent.parent / 'sources' / 'music1.mp3'  # тестирование/Hw2/code/sources/music1.mp3
        music_upload.send_keys(str(mp3_path))
```

2020-10-24 07:03 UTC, SushkaVlad commented on тестирование/Hw2/code/ui/pages/create_company_page.py
> +        music_upload.send_keys(r"C:\Users\USER\Desktop\информатика\Python\тестирование\Hw2\code\sources\music1.mp3")
Большое спасибо за замечание! Так, конечно, правильнее! Исправлю)

2020-10-24 07:05 UTC, SushkaVlad commented on тестирование/Hw2/code/ui/fixtures.py
> +        # driver = webdriver.Remote(command_executor='http://127.0.0.1:4444/wd/hub/',
Обязательно попробую) Просто, честно говоря, не успевал. А на винде я  пробовал поставить, но упорно ничего не получалось. Обязательно покопаюсь с этим)

2020-10-24 07:51 UTC, SushkaVlad commented on тестирование/Hw2/code/ui/pages/create_company_page.py
> +        music_upload.send_keys(r"C:\Users\USER\Desktop\информатика\Python\тестирование\Hw2\code\sources\music1.mp3")
Потестил create_company. И у меня такая же проблема с TimeoutException была, хотя у меня-то должно работать. Оказалось, что сам сайт даже вручную не дает загрузить то аудио, хотя раньше грузило. Может я превысил какой-то лимит?) Поменял аудио - все заработало)

2020-10-26 19:20 UTC, SK1995 commented
Хорошая работа, спасибо!
Жалко что после дедлайна, так бы максимум можно было ставить.
Поставил 8 баллов, 4 снял за первый дедлайн.

2020-10-26 19:20 UTC, SK1995 approved these changes

2020-10-26 19:20 UTC, merged