Qa python homework 3
SushkaVlad/2020-1-Atom-QA-Python-V-Sushkevich pull request #3
Opened 2020-10-21 10:36 UTC by SushkaVlad

#Домашнее задание №

Прошу @snicks92 или @z1ll1 проверить его.

Что было сделано:
Была реализована возможность авторизации в личном кабинете посредством api
Были написаны тесты на создание и удаление сегмента
Тесты запускаются в два потока

2020-10-26 22:34 UTC, snicks92 requested changes
Все ок, мелкие комменты + ребейз бы сделать на актуальный мастер, убрав старые коммиты со 2 домашкой

2020-10-26 22:34 UTC, snicks92 commented on тестирование/Hw3/code/api_client/mytarget_client.py
> +                raise RequestErrorException(f'Request "{url}" dailed with error "{error}"!')
вы все не глядя это копируете?)

2020-10-26 22:34 UTC, snicks92 commented on тестирование/Hw3/code/api_client/mytarget_client.py
> +            return False
а чего бы сразу здесь не вернуть True, если сегмент найден, не перебирая все?

2020-10-28 17:33 UTC, SushkaVlad commented on тестирование/Hw3/code/api_client/mytarget_client.py
> +            return False
Исправил)

2020-10-28 17:36 UTC, SushkaVlad commented on тестирование/Hw3/code/api_client/mytarget_client.py
> +                raise RequestErrorException(f'Request "{url}" dailed with error "{error}"!')
Поправил) Единственное, у меня честно говоря беда с ребэйзом((( Видимо, я еще пару занятий назад не понимал принципов git основных и у меня в репозитории ветки с дз создавались друг от друга, в общем треш... Я клонировал заново репозиторий с github, но понятнее не стало( Четвертое дз постараюсь уже адекватно сделать в отдельной ветке, созданной от мастера)

2020-10-29 11:59 UTC, snicks92 approved these changes

2020-10-29 11:59 UTC, merged

2020-10-29 12:01 UTC, snicks92 commented
Теперь вроде ок, и учи гит) За сдачу после дедлайна -30%